version: "3"
services:
  docker-mysql:
    image: mysql:8.0
    container_name: docker-mysql
    build: ./SQLDockerFile
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: nevertellkd
      MYSQL_DATABASE: famesphere
    volumes:
      - ./famesphere_profile.sql:/docker-entrypoint-initdb.d/famesphere_profile.sql

  springboot-app:
    image: springboot-app
    container_name: springboot-docker
    build: .
    ports:
      - 8090:443
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/famesphere
    depends_on:
      - docker-mysql