version: "3"
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: nevertellkd
      MYSQL_DATABASE: famesphere

  springboot-app:
    image: springboot-app
    build: .
    ports:
      - 8080:8090
