server :
  port : 443

  ssl:
    enabled: true
    key-alias: local_ssl2
    key-store: classpath:local-ssl2.p12
    key-store-type: PKCS12
    key-password: nevertellkd
    key-store-password: nevertellkd
